#!/bin/bash
if [ $# -gt 1 ]
then
    entry="++"
    for ((i = 1; i <= $#; i++));
    do
     entry="${entry} $i"
    done

    sudo apt-get install $1
    if [ $? -eq 0 ] 
    then
        #$2 is the group that this package belongs to
        echo $1 >> ~/sync/configstuff/packages.txt;
        echo "++ $1 $2" >> ~/sync/configstuff/frombase.txt;
    fi
fi
